Patch Python3.11 depreciation issues
NobodyXu/swaystatus pull request #54
Opened 2024-02-28 15:11 UTC by OhseyDev

2024-02-28 15:12 UTC, OhseyDev commented
Not to be finalized here.

2024-02-29 06:23 UTC, NobodyXu requested changes

2024-03-08 21:52 UTC, OhseyDev commented on src/utility.c
> +		//[[fallthrough]];
Yes it does.

2024-03-08 23:59 UTC, merged

2024-03-08 23:59 UTC, NobodyXu commented
Thanks!